-- Patch: insert missing exercises & options for lessons 2, 5, 7, 8
-- (These failed due to missing 'explanation' field in error_correction exercises)

-- ============================================================
-- LESSON 2: culture-society-norms — exercises + options
-- ============================================================
INSERT INTO exercise (lesson_id, type, difficulty, question, question_vi, correct_answer, explanation, explanation_vi, order_index) VALUES
  ((SELECT id FROM lesson WHERE slug = 'culture-society-norms'),
   'multiple_choice', 'easy',
   'Which term describes the tendency to judge other cultures by the standards of one''s own culture?',
   'Thuật ngữ nào mô tả xu hướng phán xét các nền văn hóa khác theo tiêu chuẩn của nền văn hóa mình?',
   'B',
   'Ethnocentrism is viewing one''s own culture as superior and using it as the standard to judge others. Cultural relativism is the opposite — it calls for evaluating cultures within their own context.',
   'Tự tôn văn hóa là coi văn hóa của mình là tiêu chuẩn để đánh giá các văn hóa khác. Tương đối văn hóa ngược lại.', 1),
  ((SELECT id FROM lesson WHERE slug = 'culture-society-norms'),
   'true_false', 'easy',
   'Mores are minor social conventions whose violation causes only mild embarrassment, while folkways are the core moral norms with serious social consequences.',
   'Mores là những quy ước xã hội nhỏ mà vi phạm chỉ gây bối rối nhẹ, còn folkways là chuẩn mực đạo đức cốt lõi với hậu quả xã hội nghiêm trọng.',
   'false',
   'This is reversed. Mores are the strong moral norms — violating them brings serious condemnation. Folkways are minor conventions whose violation causes only mild disapproval.',
   'Điều này bị đảo ngược. Mores là chuẩn mực đạo đức mạnh — vi phạm bị lên án nghiêm trọng. Folkways là quy ước nhỏ chỉ gây bất tiện nhẹ.', 2),
  ((SELECT id FROM lesson WHERE slug = 'culture-society-norms'),
   'fill_blank', 'easy',
   'The lifelong process through which individuals learn the norms, values, and roles of their society is called _____.',
   'Quá trình suốt đời mà qua đó cá nhân học các chuẩn mực, giá trị và vai trò xã hội được gọi là _____.',
   'socialization',
   'Socialization is the process of internalizing cultural norms and values. Primary socialization occurs in the family; secondary socialization continues through peers, school, and media.',
   'Xã hội hóa là quá trình tiếp thu các chuẩn mực và giá trị văn hóa. Sơ cấp xảy ra trong gia đình; thứ cấp tiếp tục qua bạn bè, trường học và truyền thông.', 3),
  ((SELECT id FROM lesson WHERE slug = 'culture-society-norms'),
   'multiple_choice', 'medium',
   'The Sapir-Whorf hypothesis (linguistic relativity) proposes that:',
   'Giả thuyết Sapir-Whorf (tương đối ngôn ngữ) đề xuất rằng:',
   'B',
   'The Sapir-Whorf hypothesis argues that the language we speak shapes how we perceive and think about reality. The "weak" version argues language influences thought; the "strong" version argues it determines thought.',
   'Giả thuyết Sapir-Whorf lập luận ngôn ngữ chúng ta nói định hình cách nhận thức thực tại. Phiên bản yếu: ảnh hưởng tư duy; phiên bản mạnh: quyết định tư duy.', 4),
  ((SELECT id FROM lesson WHERE slug = 'culture-society-norms'),
   'error_correction', 'medium',
   'Correct this statement: "Cultural relativism means accepting all cultural practices as morally equal and refusing to criticize any aspect of another culture."',
   'Sửa câu này: "Tương đối văn hóa có nghĩa là chấp nhận mọi thực hành văn hóa là bình đẳng về đạo đức và từ chối phê bình bất kỳ khía cạnh nào của văn hóa khác."',
   'Cultural relativism means understanding and evaluating practices within their own cultural context, not judging by external standards — it does not require moral acceptance of all practices.',
   'The statement overstates cultural relativism — it is a methodological tool for understanding cultures in context, not a moral obligation to approve all practices as equally valid.',
   'Câu này phóng đại tương đối văn hóa. Đây là công cụ phương pháp luận để hiểu, không phải nghĩa vụ đạo đức phê duyệt mọi thực hành.', 5);

INSERT INTO exercise_option (exercise_id, label, content, content_vi) VALUES
  ((SELECT id FROM exercise WHERE lesson_id = (SELECT id FROM lesson WHERE slug = 'culture-society-norms') AND order_index = 1),
   'A', 'Cultural relativism', 'Tương đối văn hóa'),
  ((SELECT id FROM exercise WHERE lesson_id = (SELECT id FROM lesson WHERE slug = 'culture-society-norms') AND order_index = 1),
   'B', 'Ethnocentrism', 'Tự tôn văn hóa'),
  ((SELECT id FROM exercise WHERE lesson_id = (SELECT id FROM lesson WHERE slug = 'culture-society-norms') AND order_index = 1),
   'C', 'Cultural diffusion', 'Lan truyền văn hóa'),
  ((SELECT id FROM exercise WHERE lesson_id = (SELECT id FROM lesson WHERE slug = 'culture-society-norms') AND order_index = 1),
   'D', 'Xenocentrism', 'Sùng bái văn hóa ngoại'),
  ((SELECT id FROM exercise WHERE lesson_id = (SELECT id FROM lesson WHERE slug = 'culture-society-norms') AND order_index = 4),
   'A', 'All languages express ideas in fundamentally equivalent ways', 'Mọi ngôn ngữ đều thể hiện ý tưởng theo cách tương đương nhau'),
  ((SELECT id FROM exercise WHERE lesson_id = (SELECT id FROM lesson WHERE slug = 'culture-society-norms') AND order_index = 4),
   'B', 'The language we speak influences how we perceive and think about reality', 'Ngôn ngữ chúng ta nói ảnh hưởng đến cách chúng ta nhận thức và suy nghĩ về thực tại'),
  ((SELECT id FROM exercise WHERE lesson_id = (SELECT id FROM lesson WHERE slug = 'culture-society-norms') AND order_index = 4),
   'C', 'Thought is completely independent of the language we speak', 'Tư duy hoàn toàn độc lập với ngôn ngữ chúng ta nói'),
  ((SELECT id FROM exercise WHERE lesson_id = (SELECT id FROM lesson WHERE slug = 'culture-society-norms') AND order_index = 4),
   'D', 'Cultural change always precedes and drives linguistic change', 'Thay đổi văn hóa luôn đi trước và thúc đẩy thay đổi ngôn ngữ');

-- ============================================================
-- LESSON 5: criminology-basics — exercises + options
-- ============================================================
INSERT INTO exercise (lesson_id, type, difficulty, question, question_vi, correct_answer, explanation, explanation_vi, order_index) VALUES
  ((SELECT id FROM lesson WHERE slug = 'criminology-basics'),
   'multiple_choice', 'easy',
   'Classical criminology argues that criminal behavior is best explained by:',
   'Tội phạm học cổ điển lập luận rằng hành vi tội phạm được giải thích tốt nhất bởi:',
   'B',
   'Classical criminology (Beccaria, Bentham) argues that people are rational actors who weigh costs and benefits. Crime occurs when anticipated benefits exceed expected costs (punishment). Deterrence reduces crime by increasing perceived costs.',
   'Tội phạm học cổ điển lập luận mọi người cân nhắc chi phí và lợi ích. Tội phạm xảy ra khi lợi ích dự kiến vượt quá chi phí (hình phạt).', 1),
  ((SELECT id FROM lesson WHERE slug = 'criminology-basics'),
   'true_false', 'easy',
   'According to Merton''s strain theory, crime rates tend to be highest among those who lack access to legitimate means to achieve socially valued goals.',
   'Theo lý thuyết căng thẳng của Merton, tỷ lệ tội phạm có xu hướng cao nhất ở những người thiếu khả năng tiếp cận các phương tiện hợp pháp để đạt được các mục tiêu có giá trị xã hội.',
   'true',
   'Merton argued that lower-class individuals face the greatest strain because they share cultural goals (the American Dream) but have less access to legitimate means. "Innovation" using illegal means is one adaptation.',
   'Merton lập luận tầng lớp thấp hơn đối mặt với căng thẳng lớn nhất vì họ chia sẻ mục tiêu văn hóa nhưng có ít phương tiện hợp pháp hơn.', 2),
  ((SELECT id FROM lesson WHERE slug = 'criminology-basics'),
   'fill_blank', 'easy',
   'Howard Becker''s _____ theory argues that deviance is not a quality of the act itself, but a consequence of the social rules and sanctions applied by others.',
   'Lý thuyết _____ của Howard Becker lập luận rằng sự lệch lạc không phải là phẩm chất của hành động mà là hệ quả của các quy tắc và chế tài xã hội được áp dụng bởi người khác.',
   'labeling',
   'Labeling theory (Becker, 1963) argues that "deviant" is a label applied by those with power to define rules. Once labeled, individuals may adopt a deviant identity (secondary deviance) and face stigma.',
   'Lý thuyết gán nhãn lập luận "lệch lạc" là nhãn được áp dụng bởi những người có quyền lực định nghĩa quy tắc.', 3),
  ((SELECT id FROM lesson WHERE slug = 'criminology-basics'),
   'multiple_choice', 'medium',
   'In Merton''s typology of adaptation, an "innovator" is someone who:',
   'Trong phân loại cách thích nghi của Merton, một "người đổi mới" là người:',
   'B',
   'Merton''s "innovator" accepts the cultural goal (financial success) but rejects legitimate means and adopts illegitimate ones (theft, drug dealing). This adaptation is most associated with conventional crime.',
   '"Người đổi mới" của Merton chấp nhận mục tiêu văn hóa nhưng từ chối phương tiện hợp pháp và áp dụng phương tiện bất hợp pháp.', 4),
  ((SELECT id FROM lesson WHERE slug = 'criminology-basics'),
   'error_correction', 'medium',
   'Correct this statement: "Positivist criminology argues that criminals freely choose to commit crimes based on rational calculation of benefits versus risks."',
   'Sửa câu này: "Tội phạm học thực chứng lập luận rằng tội phạm tự do lựa chọn phạm tội dựa trên tính toán hợp lý về lợi ích so với rủi ro."',
   'This describes classical criminology. Positivist criminology argues that criminal behavior is determined by factors beyond individual free choice — including biological, psychological, and social/environmental factors.',
   'The statement describes classical (rational choice) criminology. Positivist criminology (Lombroso, later social positivists) searches for deterministic causes — biological, psychological, or social — that push people toward crime.',
   'Điều này mô tả tội phạm học cổ điển. Tội phạm học thực chứng tìm kiếm các nguyên nhân tất định — sinh học, tâm lý hoặc xã hội.', 5);

INSERT INTO exercise_option (exercise_id, label, content, content_vi) VALUES
  ((SELECT id FROM exercise WHERE lesson_id = (SELECT id FROM lesson WHERE slug = 'criminology-basics') AND order_index = 1),
   'A', 'Biological defects that predispose certain individuals to criminal behavior', 'Khiếm khuyết sinh học khiến một số cá nhân dễ có hành vi tội phạm'),
  ((SELECT id FROM exercise WHERE lesson_id = (SELECT id FROM lesson WHERE slug = 'criminology-basics') AND order_index = 1),
   'B', 'Rational choice — offenders weigh costs and benefits before acting', 'Lựa chọn hợp lý — người phạm tội cân nhắc chi phí và lợi ích trước khi hành động'),
  ((SELECT id FROM exercise WHERE lesson_id = (SELECT id FROM lesson WHERE slug = 'criminology-basics') AND order_index = 1),
   'C', 'Social inequality and lack of access to legitimate opportunities', 'Bất bình đẳng xã hội và thiếu khả năng tiếp cận các cơ hội hợp pháp'),
  ((SELECT id FROM exercise WHERE lesson_id = (SELECT id FROM lesson WHERE slug = 'criminology-basics') AND order_index = 1),
   'D', 'Childhood trauma and early adverse experiences', 'Chấn thương thời thơ ấu và những trải nghiệm bất lợi sớm'),
  ((SELECT id FROM exercise WHERE lesson_id = (SELECT id FROM lesson WHERE slug = 'criminology-basics') AND order_index = 4),
   'A', 'Accepts both the cultural goals and the legitimate means to achieve them', 'Chấp nhận cả mục tiêu văn hóa và các phương tiện hợp pháp để đạt được chúng'),
  ((SELECT id FROM exercise WHERE lesson_id = (SELECT id FROM lesson WHERE slug = 'criminology-basics') AND order_index = 4),
   'B', 'Accepts cultural goals but rejects legitimate means, using illegitimate methods instead', 'Chấp nhận mục tiêu văn hóa nhưng từ chối phương tiện hợp pháp, thay vào đó sử dụng phương pháp bất hợp pháp'),
  ((SELECT id FROM exercise WHERE lesson_id = (SELECT id FROM lesson WHERE slug = 'criminology-basics') AND order_index = 4),
   'C', 'Rejects cultural goals but follows conventional behavior through legitimate means', 'Từ chối mục tiêu văn hóa nhưng theo đuổi hành vi thông thường qua các phương tiện hợp pháp'),
  ((SELECT id FROM exercise WHERE lesson_id = (SELECT id FROM lesson WHERE slug = 'criminology-basics') AND order_index = 4),
   'D', 'Rejects both cultural goals and legitimate means, withdrawing from society', 'Từ chối cả mục tiêu văn hóa và phương tiện hợp pháp, rút khỏi xã hội');

-- ============================================================
-- LESSON 7: learning-theories — exercises + options
-- ============================================================
INSERT INTO exercise (lesson_id, type, difficulty, question, question_vi, correct_answer, explanation, explanation_vi, order_index) VALUES
  ((SELECT id FROM lesson WHERE slug = 'learning-theories'),
   'multiple_choice', 'easy',
   'B.F. Skinner''s operant conditioning theory is based on:',
   'Lý thuyết điều kiện hóa hành động của B.F. Skinner dựa trên:',
   'B',
   'Operant conditioning holds that behavior is shaped by its consequences — reinforcement increases behavior and punishment decreases it. Skinner''s "Skinner box" demonstrated animals could be trained through systematic reinforcement schedules.',
   'Điều kiện hóa hành động cho rằng hành vi được định hình bởi hậu quả — củng cố tăng hành vi và hình phạt giảm hành vi.', 1),
  ((SELECT id FROM lesson WHERE slug = 'learning-theories'),
   'true_false', 'easy',
   'Vygotsky''s Zone of Proximal Development (ZPD) refers to tasks that a learner can complete entirely independently without any assistance.',
   'Vùng Phát Triển Gần Nhất (ZPD) của Vygotsky đề cập đến các nhiệm vụ mà người học có thể hoàn thành hoàn toàn độc lập mà không cần bất kỳ sự hỗ trợ nào.',
   'false',
   'The ZPD is the gap between what a learner can do independently and what they can accomplish with guidance. Tasks within the ZPD are achievable with support but not yet mastered independently — that is where growth occurs.',
   'ZPD là khoảng cách giữa những gì học sinh có thể làm độc lập và những gì họ có thể hoàn thành với sự hướng dẫn.', 2),
  ((SELECT id FROM lesson WHERE slug = 'learning-theories'),
   'fill_blank', 'easy',
   'Piaget identified four stages of cognitive development: sensorimotor, preoperational, concrete operational, and _____ operational.',
   'Piaget xác định bốn giai đoạn phát triển nhận thức: cảm giác-vận động, tiền thao tác, thao tác cụ thể và thao tác _____.',
   'formal',
   'The formal operational stage (age 12+) is when adolescents develop the ability to think abstractly, reason hypothetically, and use systematic logic including scientific reasoning and philosophical thinking.',
   'Giai đoạn thao tác hình thức (12+) là khi thanh thiếu niên phát triển khả năng tư duy trừu tượng và lý luận giả thuyết.', 3),
  ((SELECT id FROM lesson WHERE slug = 'learning-theories'),
   'multiple_choice', 'medium',
   'Albert Bandura''s social learning theory emphasizes that learning occurs through:',
   'Lý thuyết học tập xã hội của Albert Bandura nhấn mạnh rằng học tập xảy ra qua:',
   'B',
   'Bandura argued that much learning happens through observing others (models). His Bobo doll experiments (1961) showed children imitated aggressive behavior without direct reinforcement. Key addition: self-efficacy (belief in one''s ability) strongly predicts achievement.',
   'Bandura lập luận nhiều học tập xảy ra qua quan sát người khác (mô hình). Thí nghiệm búp bê Bobo (1961) cho thấy trẻ bắt chước hành vi hung hăng.', 4),
  ((SELECT id FROM lesson WHERE slug = 'learning-theories'),
   'error_correction', 'medium',
   'Correct this statement: "Behaviorism focuses on internal mental processes, cognitive structures, and how learners mentally organize information."',
   'Sửa câu này: "Thuyết hành vi tập trung vào các quá trình tinh thần bên trong, cấu trúc nhận thức và cách người học tổ chức thông tin về mặt tinh thần."',
   'This describes cognitivism. Behaviorism focuses exclusively on observable behavior and the role of environmental stimuli and consequences — it explicitly rejects internal mental states as unmeasurable.',
   'The statement describes cognitivism (Piaget, schema theory). Behaviorism (Watson, Skinner) explicitly rejected internal mental processes as unscientific — only observable stimulus-response connections matter.',
   'Điều này mô tả thuyết nhận thức. Thuyết hành vi tập trung vào hành vi có thể quan sát và từ chối các trạng thái tinh thần bên trong.', 5);

INSERT INTO exercise_option (exercise_id, label, content, content_vi) VALUES
  ((SELECT id FROM exercise WHERE lesson_id = (SELECT id FROM lesson WHERE slug = 'learning-theories') AND order_index = 1),
   'A', 'Classical conditioning — associating a neutral stimulus with an unconditioned response', 'Điều kiện hóa cổ điển — liên kết kích thích trung tính với phản ứng không điều kiện'),
  ((SELECT id FROM exercise WHERE lesson_id = (SELECT id FROM lesson WHERE slug = 'learning-theories') AND order_index = 1),
   'B', 'The role of consequences — reinforcement increases behavior, punishment decreases it', 'Vai trò của hậu quả — củng cố tăng hành vi, hình phạt giảm hành vi'),
  ((SELECT id FROM exercise WHERE lesson_id = (SELECT id FROM lesson WHERE slug = 'learning-theories') AND order_index = 1),
   'C', 'Observational learning and imitation of models in social contexts', 'Học quan sát và bắt chước người mẫu trong bối cảnh xã hội'),
  ((SELECT id FROM exercise WHERE lesson_id = (SELECT id FROM lesson WHERE slug = 'learning-theories') AND order_index = 1),
   'D', 'Internal cognitive schemas that organize and interpret new information', 'Các sơ đồ nhận thức bên trong tổ chức và giải thích thông tin mới'),
  ((SELECT id FROM exercise WHERE lesson_id = (SELECT id FROM lesson WHERE slug = 'learning-theories') AND order_index = 4),
   'A', 'Unconscious drives and unresolved psychosexual conflicts', 'Các động lực vô thức và xung đột tâm dục chưa được giải quyết'),
  ((SELECT id FROM exercise WHERE lesson_id = (SELECT id FROM lesson WHERE slug = 'learning-theories') AND order_index = 4),
   'B', 'Observation and imitation of models, requiring attention, retention, reproduction, and motivation', 'Quan sát và bắt chước người mẫu, đòi hỏi sự chú ý, lưu giữ, tái tạo và động lực'),
  ((SELECT id FROM exercise WHERE lesson_id = (SELECT id FROM lesson WHERE slug = 'learning-theories') AND order_index = 4),
   'C', 'Fixed developmental stages that unfold as children mature biologically', 'Các giai đoạn phát triển cố định xuất hiện khi trẻ em trưởng thành về mặt sinh học'),
  ((SELECT id FROM exercise WHERE lesson_id = (SELECT id FROM lesson WHERE slug = 'learning-theories') AND order_index = 4),
   'D', 'Direct reinforcement schedules applied systematically to modify behavior', 'Lịch trình củng cố trực tiếp được áp dụng có hệ thống để thay đổi hành vi');

-- ============================================================
-- LESSON 8: effective-teaching-methods — exercises + options
-- ============================================================
INSERT INTO exercise (lesson_id, type, difficulty, question, question_vi, correct_answer, explanation, explanation_vi, order_index) VALUES
  ((SELECT id FROM lesson WHERE slug = 'effective-teaching-methods'),
   'multiple_choice', 'easy',
   'Formative assessment is best described as:',
   'Đánh giá hình thành được mô tả tốt nhất là:',
   'B',
   'Formative assessment is ongoing assessment during the learning process to monitor progress and adjust instruction. Examples include exit tickets, think-pair-share, and quick polls. Distinct from summative assessment, which measures achievement after learning.',
   'Đánh giá hình thành là đánh giá liên tục trong khi học tập để theo dõi tiến độ và điều chỉnh giảng dạy.', 1),
  ((SELECT id FROM lesson WHERE slug = 'effective-teaching-methods'),
   'true_false', 'easy',
   'In cooperative learning, individual accountability is not important because only the group outcome matters — as long as the group produces a good result, all members benefit equally.',
   'Trong học tập hợp tác, trách nhiệm cá nhân không quan trọng vì chỉ kết quả nhóm mới quan trọng.',
   'false',
   'Individual accountability is one of Johnson & Johnson''s five essential elements. Without it, "social loafing" occurs — some members contribute little while benefiting from others'' work. True cooperative learning requires each member to be accountable for their individual contribution.',
   'Trách nhiệm cá nhân là một trong năm yếu tố thiết yếu của Johnson & Johnson. Không có nó, "lười nhác xã hội" xảy ra.', 2),
  ((SELECT id FROM lesson WHERE slug = 'effective-teaching-methods'),
   'fill_blank', 'easy',
   'Benjamin Bloom''s _____, revised in 2001, classifies cognitive learning objectives from lower-order (remember, understand) to higher-order (analyze, evaluate, create).',
   'Bảng phân loại _____ của Benjamin Bloom, được sửa đổi năm 2001, phân loại mục tiêu học tập nhận thức từ bậc thấp đến bậc cao.',
   'Taxonomy',
   'Bloom''s Taxonomy provides a hierarchical framework for writing learning objectives. The revised version (2001) changed "Synthesis" to "Create" and converted noun labels to verbs. It guides teachers to design assessments across all cognitive levels.',
   'Thang đo Bloom cung cấp khung phân cấp để viết mục tiêu học tập. Phiên bản sửa đổi (2001) chuyển nhãn danh từ thành động từ.', 3),
  ((SELECT id FROM lesson WHERE slug = 'effective-teaching-methods'),
   'multiple_choice', 'medium',
   'Differentiated instruction involves:',
   'Dạy học phân hóa bao gồm:',
   'B',
   'Differentiated instruction (Tomlinson) means adjusting content, process, product, and environment based on students'' readiness, interests, and learning profiles — not just assigning more work to advanced learners.',
   'Dạy học phân hóa (Tomlinson) điều chỉnh nội dung, quy trình, sản phẩm và môi trường dựa trên sự sẵn sàng, sở thích và hồ sơ học tập của học sinh.', 4),
  ((SELECT id FROM lesson WHERE slug = 'effective-teaching-methods'),
   'error_correction', 'medium',
   'Correct this statement: "Direct instruction is ineffective for teaching foundational skills because it is teacher-centered and prevents student discovery and deep understanding."',
   'Sửa câu này: "Dạy học trực tiếp không hiệu quả để dạy các kỹ năng nền tảng vì nó tập trung vào giáo viên và ngăn chặn sự khám phá và hiểu sâu."',
   'Research consistently shows direct instruction is highly effective for teaching explicit skills and foundational knowledge. The I Do / We Do / You Do model systematically transfers responsibility and supports both skill acquisition and deep understanding.',
   'Rosenshine''s Principles and Hattie''s meta-analyses confirm direct instruction has large effect sizes. The I Do/We Do/You Do model is initially teacher-centered but systematically transfers ownership to students.',
   'Nghiên cứu nhất quán cho thấy dạy học trực tiếp rất hiệu quả để dạy kỹ năng tường minh và kiến thức nền tảng.', 5);

INSERT INTO exercise_option (exercise_id, label, content, content_vi) VALUES
  ((SELECT id FROM exercise WHERE lesson_id = (SELECT id FROM lesson WHERE slug = 'effective-teaching-methods') AND order_index = 1),
   'A', 'A final exam that measures cumulative learning at the end of a course', 'Kỳ thi cuối khóa đo lường kiến thức tích lũy ở cuối khóa học'),
  ((SELECT id FROM exercise WHERE lesson_id = (SELECT id FROM lesson WHERE slug = 'effective-teaching-methods') AND order_index = 1),
   'B', 'Ongoing assessment during instruction to monitor progress and guide teaching decisions', 'Đánh giá liên tục trong khi giảng dạy để theo dõi tiến độ và hướng dẫn quyết định dạy học'),
  ((SELECT id FROM exercise WHERE lesson_id = (SELECT id FROM lesson WHERE slug = 'effective-teaching-methods') AND order_index = 1),
   'C', 'Standardized testing that allows comparison of student performance across schools', 'Kiểm tra chuẩn hóa cho phép so sánh kết quả học sinh giữa các trường'),
  ((SELECT id FROM exercise WHERE lesson_id = (SELECT id FROM lesson WHERE slug = 'effective-teaching-methods') AND order_index = 1),
   'D', 'Peer assessment where students evaluate each other''s work using rubrics', 'Đánh giá đồng đẳng nơi học sinh đánh giá công việc của nhau bằng rubric'),
  ((SELECT id FROM exercise WHERE lesson_id = (SELECT id FROM lesson WHERE slug = 'effective-teaching-methods') AND order_index = 4),
   'A', 'Teaching all students the same content at the same pace using identical methods', 'Dạy tất cả học sinh cùng nội dung với cùng tốc độ sử dụng phương pháp giống nhau'),
  ((SELECT id FROM exercise WHERE lesson_id = (SELECT id FROM lesson WHERE slug = 'effective-teaching-methods') AND order_index = 4),
   'B', 'Adjusting content, process, product, and environment based on student readiness and learning profiles', 'Điều chỉnh nội dung, quy trình, sản phẩm và môi trường dựa trên sự sẵn sàng và hồ sơ học tập của học sinh'),
  ((SELECT id FROM exercise WHERE lesson_id = (SELECT id FROM lesson WHERE slug = 'effective-teaching-methods') AND order_index = 4),
   'C', 'Permanently grouping students by ability level to allow targeted instruction', 'Phân nhóm học sinh vĩnh viễn theo trình độ để cho phép dạy học có mục tiêu'),
  ((SELECT id FROM exercise WHERE lesson_id = (SELECT id FROM lesson WHERE slug = 'effective-teaching-methods') AND order_index = 4),
   'D', 'Using technology platforms to deliver personalized adaptive learning for each student', 'Sử dụng nền tảng công nghệ để cung cấp học tập thích nghi cá nhân hóa cho mỗi học sinh');
